"""Common English first-name list for A4 low-info within-UCID policy."""

# Compact high-frequency US given names (lowercase). Used when a mention is a
# single token that matches this set → valid mention, merge only within UCID.
COMMON_FIRST_NAMES = {
    "aaron", "adam", "adrian", "alan", "albert", "alex", "alexander", "alfred",
    "alice", "alison", "allen", "allison", "amanda", "amy", "andrea", "andrew",
    "angela", "ann", "anna", "anne", "anthony", "antonio", "arthur", "ashley",
    "barbara", "barry", "benjamin", "bernard", "beth", "betty", "beverly",
    "bill", "billy", "bobby", "bradley", "brandon", "brenda", "brian", "bruce",
    "bryan", "carl", "carlos", "carol", "carolyn", "catherine", "charles",
    "charlotte", "chris", "christian", "christina", "christine", "christopher",
    "cindy", "claire", "clara", "clarence", "claude", "clayton", "clifford",
    "clinton", "clyde", "colin", "colleen", "connie", "corey", "cory", "craig",
    "crystal", "curtis", "cynthia", "dale", "dan", "dana", "daniel", "danielle",
    "danny", "darrell", "darren", "david", "dawn", "dean", "debra", "deborah",
    "dennis", "derek", "diana", "diane", "donald", "donna", "doris", "dorothy",
    "douglas", "duane", "dustin", "dwayne", "dylan", "earl", "eddie", "edgar",
    "edith", "edward", "edwin", "eileen", "elaine", "eleanor", "elizabeth",
    "ellen", "emily", "eric", "erica", "erik", "erin", "ernest", "eugene",
    "eva", "evan", "evelyn", "faith", "felix", "fernando", "florence", "floyd",
    "frances", "francis", "frank", "franklin", "fred", "frederick", "gabriel",
    "gail", "gary", "gavin", "gene", "george", "gerald", "gilbert", "gina",
    "glenn", "gloria", "gordon", "grace", "gregory", "guy", "gwendolyn",
    "harold", "harry", "harvey", "helen", "henry", "herbert", "herman", "holly",
    "howard", "hugh", "ian", "irene", "isaac", "ivan", "jack", "jacob", "james",
    "jamie", "jane", "janet", "janice", "jared", "jason", "jay", "jean", "jeff",
    "jeffrey", "jennifer", "jeremy", "jerry", "jesse", "jessica", "jill", "jim",
    "jimmy", "joan", "joann", "joanna", "joanne", "joe", "joel", "john",
    "johnny", "jon", "jonathan", "jordan", "jose", "joseph", "josephine",
    "josh", "joshua", "joyce", "juan", "judith", "judy", "julia", "julian",
    "julie", "justin", "karen", "karl", "kate", "katherine", "kathleen",
    "kathryn", "kathy", "kay", "keith", "kelly", "ken", "kenneth", "kevin",
    "kim", "kimberly", "kirk", "kyle", "larry", "laura", "lauren", "lawrence",
    "lee", "leo", "leon", "leonard", "leroy", "leslie", "lester", "lewis",
    "liam", "lillian", "linda", "lindsay", "lisa", "lloyd", "lois", "loren",
    "lori", "louis", "louise", "lucas", "luis", "luke", "lynn", "madison",
    "manuel", "marc", "marcia", "marcus", "margaret", "maria", "marie",
    "marilyn", "mario", "marion", "mark", "marlene", "marsha", "marshall",
    "martha", "martin", "marvin", "mary", "mason", "matthew", "maureen",
    "maurice", "max", "megan", "melanie", "melvin", "michael", "michelle",
    "miguel", "mike", "mildred", "milton", "mitchell", "monica", "morgan",
    "morris", "nancy", "naomi", "natalie", "nathan", "nathaniel", "neil",
    "nelson", "nicholas", "nicole", "nina", "noah", "norman", "oliver",
    "olivia", "oscar", "owen", "pam", "pamela", "pat", "patricia", "patrick",
    "paul", "paula", "pearl", "pedro", "peggy", "penny", "perry", "peter",
    "philip", "phillip", "phyllis", "preston", "rachel", "ralph", "ramon",
    "randall", "randy", "raymond", "rebecca", "regina", "rene", "renee",
    "rhonda", "ricardo", "richard", "rick", "ricky", "rita", "rob", "robert",
    "robin", "roger", "roland", "ron", "ronald", "rosa", "rose", "ross", "roy",
    "ruben", "russell", "ruth", "ryan", "sally", "sam", "samuel", "sandra",
    "sara", "sarah", "scott", "sean", "sergio", "seth", "shannon", "sharon",
    "shaun", "shawn", "sheila", "shelley", "sherri", "sherry", "shirley",
    "sidney", "simon", "sophia", "stacey", "stacy", "stanley", "stephanie",
    "stephen", "steve", "steven", "stewart", "stuart", "sue", "susan",
    "suzanne", "sydney", "sylvia", "tamara", "tammy", "tanya", "taylor", "ted",
    "teresa", "terrance", "terrence", "terry", "thelma", "theodore", "theresa",
    "thomas", "tiffany", "tim", "timothy", "tina", "todd", "tom", "tommy",
    "toni", "tony", "tracey", "tracy", "travis", "troy", "tyler", "tyrone",
    "valerie", "vanessa", "vernon", "veronica", "vicki", "vickie", "victor",
    "victoria", "vincent", "viola", "violet", "virginia", "vivian", "wade",
    "wallace", "walter", "wanda", "warren", "wayne", "wendy", "wesley",
    "whitney", "willard", "william", "willie", "wilson", "wendy", "zachary",
}
